#!/usr/bin/env node
// Automated deployment script for CWB GCP Firebase infrastructure.
// Usage:
//   npm run deploy                  (deploys hosting + firestore rules)
//   npm run deploy -- --all         (deploys hosting + firestore + cloud functions)

import { execSync } from "node:child_process";
import { writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadEnv } from "./load-env.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");
const gcpDir = join(rootDir, "platforms", "gcp");
const cloudIngestDir = join(gcpDir, "cloud-ingest");

const deployFunctions = process.argv.includes("--all") || process.argv.includes("--functions");

console.log("1. Running Privacy Compliance Gate...");
try {
    const gateOutput = execSync("node tools/privacy-gate/privacy-gate.mjs", { cwd: rootDir, encoding: "utf8" });
    console.log(gateOutput);
    const securityOutput = execSync("node tools/security-gate/security-gate.mjs", { cwd: rootDir, encoding: "utf8" });
    console.log(securityOutput);
} catch (error) {
    console.error("Privacy or security gate failed! Aborting deployment.");
    if (error.stdout) console.error(error.stdout);
    process.exit(1);
}

if (deployFunctions) {
    console.log("2. Testing Cloud Function authentication controls...");
    try {
        execSync("npm test", { cwd: cloudIngestDir, stdio: "inherit" });
    } catch {
        console.error("Cloud Function tests failed! Aborting deployment.");
        process.exit(1);
    }
}

console.log("3. Preparing production frontend configuration...");
const prodEnvPath = "../production.env";
if (!existsSync(join(rootDir, "production.env"))) {
    console.error("Error: production.env is required for deployment.");
    process.exit(1);
}
const env = loadEnv(prodEnvPath);

if (!env.FIREBASE_PROJECT_ID || !env.FIREBASE_API_KEY || !env.FIREBASE_APP_CHECK_SITE_KEY) {
    console.error(`Error: Missing FIREBASE_PROJECT_ID, FIREBASE_API_KEY, or FIREBASE_APP_CHECK_SITE_KEY in ${prodEnvPath.replace("../", "")}`);
    process.exit(1);
}

const configContent = `// Auto-generated by tools/deploy.mjs - DO NOT EDIT MANUALLY
export const firebaseConfig = {
    apiKey: ${JSON.stringify(env.FIREBASE_API_KEY)},
    authDomain: ${JSON.stringify(env.FIREBASE_AUTH_DOMAIN || `${env.FIREBASE_PROJECT_ID}.firebaseapp.com`)},
    projectId: ${JSON.stringify(env.FIREBASE_PROJECT_ID)},
    storageBucket: ${JSON.stringify(env.FIREBASE_STORAGE_BUCKET || `${env.FIREBASE_PROJECT_ID}.firebasestorage.app`)},
    messagingSenderId: ${JSON.stringify(env.FIREBASE_MESSAGING_SENDER_ID || "")},
    appId: ${JSON.stringify(env.FIREBASE_APP_ID || "")},
    appCheckSiteKey: ${JSON.stringify(env.FIREBASE_APP_CHECK_SITE_KEY)},
    region: ${JSON.stringify(env.GCP_REGION || env.FIREBASE_REGION || "us-west1")}
};
`;

const configPath = join(gcpDir, "frontend", "firebase-config.js");
writeFileSync(configPath, configContent, "utf8");
console.log(`   Updated ${configPath}`);

console.log("4. Deploying to Firebase...");
const targets = deployFunctions ? "hosting,firestore,functions" : "hosting,firestore";
try {
    const deployCmd = `npx --yes firebase-tools@15.30.0 deploy --only ${targets} --force`;
    console.log(`   Running: ${deployCmd}`);
    const output = execSync(deployCmd, { cwd: gcpDir, stdio: "inherit" });
    console.log("\nDeployment completed successfully!");
} catch (error) {
    console.error("\nFirebase deployment failed.");
    process.exit(1);
}
